-
 name: 'Initial commands'
 hosts: localhost
 vars:
  gitPath: 'https://github.com/Tanmay-More/Login-Page.git'
  repoName: 'Login-Page'
  appPath: '/home/ubuntu/workspace/sample-job/{{repoName}}'
  appInPath: '/home/ubuntu/workspace/sample-job'
 tasks:
  -
   name: 'checking files'
   command: chdir='{{appInPath}}' ls
   register: files_list
  -
   name: 'updating package list'
   shell: 'sudo apt update'
   when: files_list.stdout.find("login-app") == -1
  -
   name: 'installing curl'
   shell: 'sudo apt install curl'
   when: files_list.stdout.find("login-app") == -1
  -
   name: 'get node js package using curl'
   shell: 'curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -'
   when: files_list.stdout.find("login-app") == -1
  -
   name: 'install node js'
   command: 'sudo apt-get install -y nodejs'
   when: files_list.stdout.find("login-app") == -1
  -
   name: 'clone git repo'
   command: 'git clone {{gitPath}}'
  -
   name: 'delete old app before updating to new one'
   command: chdir='{{appInPath}}' rm -rf login-app
   when: files_list.stdout.find("login-app") != -1
  -
   name: 'create new app dir'
   command: chdir='{{appInPath}}' mkdir login-app
  -
   name: 'move files to new app dir'
   shell: mv {{appInPath}}/Login-Page/* {{appInPath}}/login-app
  -
   name: 'remove old dir'
   command: chdir='{{appInPath}}' rm -rf '{{repoName}}'
  -
   name: 'install dependencies'
   command: chdir='{{appInPath}}/login-app' npm install
  -
   name: 'make script executable'
   shell: chdir={{appInPath}}/login-app chmod +x new.sh
  -
   name: 'start running app'
   shell: chdir={{appInPath}}/login-app ./new.sh